// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp_02.Data;

#nullable disable

namespace asp_02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006142702_AddAuthorImage")]
    partial class AddAuthorImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("asp_02.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("asp_02.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Електроніка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Побут"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Аксесуари"
                        });
                });

            modelBuilder.Entity("asp_02.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 15,
                            CategoryId = 1,
                            Description = "Дисплей 120 Гц, потрійна камера.",
                            Image = "https://picsum.photos",
                            Name = "Смартфон Alpha",
                            Price = 18500.00m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 8,
                            CategoryId = 1,
                            Description = "Тонкий металевий корпус, 16 ГБ ОЗП.",
                            Image = "https://picsum.photos",
                            Name = "Ноутбук MateBook",
                            Price = 34000.00m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 25,
                            CategoryId = 1,
                            Description = "Активне шумозаглушення.",
                            Image = "https://picsum.photos",
                            Name = "Бездротові Навушники",
                            Price = 4200.00m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 12,
                            CategoryId = 1,
                            Description = "Моніторинг пульсу та крокомір.",
                            Image = "https://picsum.photos",
                            Name = "Смарт-годинник Active",
                            Price = 5900.00m
                        },
                        new
                        {
                            Id = 5,
                            Amount = 7,
                            CategoryId = 1,
                            Description = "Яскравий екран для малювання.",
                            Image = "https://picsum.photos",
                            Name = "Планшет Pro 11",
                            Price = 21000.00m
                        },
                        new
                        {
                            Id = 6,
                            Amount = 5,
                            CategoryId = 2,
                            Description = "Автоматичне приготування капучино.",
                            Image = "https://picsum.photos",
                            Name = "Кавомашина Еспресо",
                            Price = 16800.00m
                        },
                        new
                        {
                            Id = 7,
                            Amount = 9,
                            CategoryId = 2,
                            Description = "Сухе та вологе прибирання.",
                            Image = "https://picsum.photos",
                            Name = "Робот-пилосос",
                            Price = 11500.00m
                        },
                        new
                        {
                            Id = 8,
                            Amount = 30,
                            CategoryId = 2,
                            Description = "Швидке закипання, корпус із скла.",
                            Image = "https://picsum.photos",
                            Name = "Електрочайник Glass",
                            Price = 1350.00m
                        },
                        new
                        {
                            Id = 9,
                            Amount = 14,
                            CategoryId = 2,
                            Description = "24 автоматичні програми.",
                            Image = "https://picsum.photos",
                            Name = "Мультиварка-Скороварка",
                            Price = 3900.00m
                        },
                        new
                        {
                            Id = 10,
                            Amount = 20,
                            CategoryId = 2,
                            Description = "Ідеально для смузі.",
                            Image = "https://picsum.photos",
                            Name = "Блендер Фітнес",
                            Price = 2100.00m
                        },
                        new
                        {
                            Id = 11,
                            Amount = 45,
                            CategoryId = 3,
                            Description = "Натуральна шкіра.",
                            Image = "https://picsum.photos",
                            Name = "Шкіряний Гаманець",
                            Price = 950.00m
                        },
                        new
                        {
                            Id = 12,
                            Amount = 18,
                            CategoryId = 3,
                            Description = "Водовідштовхувальна тканина.",
                            Image = "https://picsum.photos",
                            Name = "Рюкзак Міський",
                            Price = 1850.00m
                        },
                        new
                        {
                            Id = 13,
                            Amount = 50,
                            CategoryId = 3,
                            Description = "Швидка зарядка трьох пристроїв.",
                            Image = "https://picsum.photos",
                            Name = "Павербанк 20k mAh",
                            Price = 1600.00m
                        },
                        new
                        {
                            Id = 14,
                            Amount = 22,
                            CategoryId = 3,
                            Description = "Міцний каркас антивітер.",
                            Image = "https://picsum.photos",
                            Name = "Парасолька-Автомат",
                            Price = 750.00m
                        },
                        new
                        {
                            Id = 15,
                            Amount = 11,
                            CategoryId = 3,
                            Description = "Поляризаційні лінзи.",
                            Image = "https://picsum.photos",
                            Name = "Сонцезахисні Окуляри",
                            Price = 1200.00m
                        });
                });

            modelBuilder.Entity("asp_02.Models.Product", b =>
                {
                    b.HasOne("asp_02.Models.Author", "Author")
                        .WithMany("Products")
                        .HasForeignKey("AuthorId");

                    b.HasOne("asp_02.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("asp_02.Models.Author", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("asp_02.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
